### ISSUE TITLE
Thanks and a suggestion so more people can use your program...

### ISSUE THREAD

**Issue by meadover** [theDubW/printcase#1]
This is a great idea for a user contribution to Stata.  Thanks for writing it. I've copied it into my "PERSONAL" ado file.

Perhaps you are planning to submit your **printcase_submission.docx** to the Stata Journal.  In that case, this comment is moot.

If you are not planning to submit but are interested in disseminating your program more widely, you might want to improve its accessibility.  For example, from inside Stata the command "search printcase" comes up empty.   (Stata's web crawler apparently does not search GitHub.)  When using the user contributed "github" command, Stata can search on GitHub for your program with the command "github search printcase, in(all) language(Stata) all".  In Stata's results window, the result is: 
```
 ----------------------------------------------------------------------------------
  Repository      Username    Install  Description 
 ----------------------------------------------------------------------------------
  printcase       theDubW              A Stata command for inspecting specific
                                       cases.
                                       updated on 2022-09-21
                                       Fork:0    Star:1    Lang:Stata       

 ----------------------------------------------------------------------------------
```
But this isn't very helpful in your case, because the "Install" column is blank instead of having a clickable link.  

Another way to install directly from GitHub is with the command 

`view net from "https://raw.githubusercontent.com/theDubW/printcase/master`

But in your case that doesn't work either.  I believe that the reason both approaches fail is the absence of a -pkg- file in your repository.  To make your GitHub repository more directly accessible by Stata, you could add two additional files named "stata.toc" and "printcase.pkg" as described by Stata in "help usersite".

Another possibility would be for you to simply send an e-mail to SSC with your files attached.  Chris Baum at Boston College or a colleague will post your program and **printcase_submission.docx** for you on SSC and RePec, where it will reach more users.  Instructions are here:
[http://www.repec.org/bocode/s/sscsubmit.html ](url)

**Comment by theDubW** [comment]
I'm glad that you enjoy _printcase_ and find it useful! Thanks for the feedback, and sorry for the late response. It would certainly be a good idea to add a package file to this repository, you're right. However, I'm happy to let you know that as of a few days ago _printcase_ has officially been published in the Stata Journal, so you should be able to install it directly through Stata as you would any other new command.
Let me know if you have any other questions or suggestions. Thanks!
